services:
  db:
    image: postgres:16-alpine
    container_name: lokatus-db
    environment:
      POSTGRES_USER: lokatus
      POSTGRES_PASSWORD: lokatus
      POSTGRES_DB: lokatus
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - lokatus-network

  web:
    container_name: lokatus-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://lokatus:lokatus@db:5432/lokatus
    networks:
      - lokatus-network

volumes:
  db:

networks:
  lokatus-network:
    external: true
