import type { Metadata } from "next";
import { Inter, Bellefair } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import TanstackProviders from "@/components/providers/TanstackProvider";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-inter",
  preload: false,
});

const bellefair = Bellefair({
  weight: ["400"],
  subsets: ["hebrew"],
  display: "swap",
  variable: "--font-bellefair",
  preload: false,
});

export const metadata: Metadata = {
  title: "Lokatus Coffee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} ${bellefair.variable} antialiased`}>
        <NuqsAdapter>
          <TanstackProviders>{children}</TanstackProviders>
          <Toaster richColors />
        </NuqsAdapter>
      </body>
    </html>
  );
}
